### ISSUE TITLE
Crate cannot be used as a dependency

### ISSUE THREAD

**Issue by ryan-summers** [richardeoin/stm32h7-ethernet#1]
Because of the way this crate is written, any attempt to utilize the crate as a dependency of another project will result in a compilation error because the underlying HAL device feature needs to be specified.

Possible solutions are this crate re-exports features that can be enabled for specific devices which automatically select the necessary HAL device as a dependency.

**Comment by ryan-summers** [comment]
Sample error output:
![image](https://user-images.githubusercontent.com/8771450/80231488-b973c100-8653-11ea-967c-d11fbe540a97.png)

**Comment by richardeoin** [comment]
Thanks for reporting!

There is one case when it's possible - if you also have `stm32h7xx-hal = 0.4.0` somewhere else in your build tree with the device feature specified there. Cargo unions feature across the dependency tree. The [docs](https://docs.rs/stm32h7-ethernet/0.1.1/stm32h7_ethernet/) attempt to explain this, but the situation isn't ideal.

We're really just using `stm32h7xx-hal` for its re-exports, which tell us which sub-module of `stm32h7` to use. We could depend on `stm32h7` directly with one fixed part (the ethernet register differences between parts are minimal) - but that would mean having two copies of `stm32h7` in everybody's build tree.

Re-exporting features is also a solution, they would need to be kept up-to-date whenever the `stm32h7xx-hal` version changes. Perhaps that is a small downside.

**Comment by ryan-summers** [comment]
For reference, I believe this comes about because I'm currently using a forked version of the `stm32h7xx-hal`

**Comment by richardeoin** [comment]
That does explain it, but your use case should be supported too.

I think re-exporting the feature flags is the best way to deal with this, thanks for the suggestion.
