### ISSUE TITLE
Support usage with RTFM

### ISSUE THREAD

**Issue by ryan-summers** [richardeoin/stm32h7-ethernet#2]
While trying to use this crate with RTFM, I've run into the following issues:
1. RTFM resources cannot have generic lifetimes, so the `EthernetDMA` object has to be constructed using a descriptor ring with a `'static` lifetime. This allows the resource type to be `stm32h7_ethernet::EthernetDMA<'static>` - other lifetimes are not supported. This took a fair amount of banging my head against the wall to figure out, so it may be worth getting an example with RTFM into the `examples` folder or adding some documentation related to this.
2. Because RTFM provides a borrow of the system resources (to support concurrent access and resource sharing), the `EthernetDMA` object cannot be stored as an RTFM resource because the `&mut EthernetDMA<'_>` object does not implement the necessary `smoltcp::phy::Device` trait. Thus, both `ethernet_init()` and `smoltcp::Interface::new()` have to be run within only a single task that utilizes the network interface.

Resulting error from (2) appears as follows:
```
error[E0277]: the trait bound `for<'d> &mut stm32h7_ethernet::ethernet::EthernetDMA<'static>: smoltcp::phy::Device<'d>` is not satisfied
   --> src/main.rs:410:13
    |
410 |             net::iface::EthernetInterfaceBuilder::new(c.resources.eth_dma)
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `for<'d> smoltcp::phy::Device<'d>` is not implemented for `&mut stm32h7_ethernet::ethernet::EthernetDMA<'static>`
    |
    = help: the following implementations were found:
              <stm32h7_ethernet::ethernet::EthernetDMA<'_> as smoltcp::phy::Device<'a>>
    = note: required by `smoltcp::iface::ethernet::InterfaceBuilder`
```

Attempting to move the ethernet DMA into the interface also result in an error (understandably):

```
error[E0507]: cannot move out of `*c.resources.eth_dma` which is behind a mutable reference
   --> src/main.rs:410:55
    |
410 |             net::iface::EthernetInterfaceBuilder::new(*c.resources.eth_dma)
    |                                                       ^^^^^^^^^^^^^^^^^^^^ move occurs because `*c.resources.eth_dma` has type `stm32h7_ethernet::ethernet::EthernetDMA<'_>`, which does not implement the `Copy` trait

error: aborting due to previous error
```

**Comment by ryan-summers** [comment]
Additional note, it doesn't seem possible to construct a `smoltcp` network interface in the `idle` state for the `EthernetDMA` if the `EthernetDMA` is stored as an RTFM resource, as the resource is borrowed instead of owned. This means that the necessary `smoltcp` traits are not implemented for the borrowed object.

**Comment by richardeoin** [comment]
I've been meaning to trim down the simplest demo, so I did that and also added a 2nd example with RTFM and smoltcp. 

I think you need to pass the `EthernetDMA` to `EthernetInterfaceBuilder::new` by value. If you want access to them after that, smoltcp provides a [method for this](https://docs.rs/smoltcp/0.6.0/smoltcp/iface/struct.EthernetInterface.html#method.device).

**Comment by ryan-summers** [comment]
Closing this, the demo in https://github.com/richardeoin/stm32h7-ethernet/pull/3 is quite helpful. Thanks! :)
